export const artifacts = [
  {
    id: 'dancing-girl',
    title: 'Dancing Girl',
    eraLabel: 'c. 2500 BCE',
    period: 'Indus Valley Civilization',
    category: 'Sculpture / Bronze',
    description: 'The famous bronze statuette of a confident young woman with a coiled hairstyle and stacked bangles, cast by the lost-wax method in the Indus Valley city of Mohenjo-daro.',
    historicalContext: 'Discovered in 1926 by Ernest Mackay in the "HR area" of Mohenjo-daro. It is one of the earliest known examples of the lost-wax bronze casting technique.',
    culturalSignificance: 'An iconic symbol of the Indus Valley Civilization, showcasing the advanced metallurgical skills and artistic expression of a society that flourished over 4,000 years ago.',
    materialsTechnique: 'Cast in bronze using the cire-perdue (lost-wax) method. The figure is adorned with 24 bangles on her left arm and 4 on her right.',
    collectionName: 'National Museum, New Delhi, India',
    image: '/assets/images/01-dancing-girl.jpg',
    imageSource: 'Wikimedia Commons (photograph by Gary Todd)',
    license: 'CC0 1.0 Public Domain Dedication',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Dancing_girl_of_Mohenjo-daro.jpg'
  },
  {
    id: 'lion-capital',
    title: 'Lion Capital of Ashoka',
    eraLabel: 'c. 250 BCE',
    period: 'Mauryan Empire — reign of Emperor Ashoka · Sarnath, Uttar Pradesh, India',
    category: 'Polished Chunar sandstone',
    description: 'The crowning capital of the pillar erected by Emperor Ashoka at Sarnath, where the Buddha preached his first sermon — four addorsed lions above a frieze of the wheel of law and four animals, seated on an inverted lotus bell.',
    historicalContext: "The capital was unearthed by Friedrich Oertel's excavations of 1904–05 at Sarnath, the site of the Buddha's first sermon. It originally surmounted a monolithic pillar that once carried the Schism Edict of Ashoka. The pillar was broken, probably during the invasions of the 12th century, but the capital survives in nearly perfect condition and is exhibited in the Sarnath Museum.",
    culturalSignificance: "In 1950 the graphic representation of this capital — with the Ashoka Chakra from its abacus — was adopted as the National Emblem of India, and the chakra was placed at the centre of the National Flag of India. As art, it is the supreme achievement of Mauryan imperial sculpture: the polished surface (the Mauryan high polish) and the powerful, naturalistic lions proclaim the emperor's universal authority and the spread of dharma.",
    materialsTechnique: "Carved from a single block of fine-grained Chunar sandstone and finished with the celebrated Mauryan high polish. The abacus frieze carries four spoked wheels (dharmachakras) alternating with four sacred animals: the lion, horse, bull and elephant.",
    collectionName: 'Sarnath Museum (Archaeological Museum, ASI), Uttar Pradesh — Acc. No. A1 | H. approx. 2.15 m including base',
    image: '/assets/images/02-lion-capital.jpg',
    imageSource: 'Wikimedia Commons (photograph by Chrisi1964)',
    license: 'CC BY-SA 4.0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sarnath_capital.jpg'
  },
  {
    id: 'gandhara-buddha',
    title: 'Standing Buddha (Gandhara)',
    eraLabel: '2nd–3rd c. CE',
    period: 'Kushan Empire',
    category: 'Sculpture / Stone',
    description: 'A standing Buddha in grey schist, robed in the heavy, toga-like drapery with naturalistic folds that characterise the Greco-Buddhist art of Gandhara.',
    historicalContext: 'Emerging from the Gandhara region (modern-day Pakistan and Afghanistan) during the Kushan Empire, this style reflects the syncretism of Indian Buddhist traditions with Greco-Roman artistic influences.',
    culturalSignificance: 'Represents one of the earliest anthropomorphic depictions of the Buddha, setting a standard for Buddhist iconography that spread across Central and East Asia.',
    materialsTechnique: 'Carved from grey schist stone. The deep, heavy folds of the monastic robe (uttarasanga) are a hallmark of the Gandharan style.',
    collectionName: 'Matsuoka Museum of Art, Tokyo, Japan',
    image: '/assets/images/03-gandhara-buddha.jpg',
    imageSource: 'Wikimedia Commons (photograph by Daderot, taken on exhibit)',
    license: 'Public Domain (CC-PD)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Standing_Buddha,_Gandhara,_c._2nd-3rd_century_AD,_gray_schist_-_Matsuoka_Museum_of_Art_-_Tokyo,_Japan_-_DSC07105.JPG'
  },
  {
    id: 'sarnath-buddha',
    title: 'Buddha Preaching His First Sermon (Sarnath Buddha)',
    eraLabel: '5th c. CE',
    period: 'Gupta Empire',
    category: 'Sculpture / Stone',
    description: 'The Sarnath Buddha in the dharmachakra-pravartana posture — the classic Gupta image of the Buddha delivering his first sermon in the Deer Park.',
    historicalContext: 'Created during the Gupta period, often considered the "Golden Age" of Indian art. It was found in the ruins of Sarnath, near Varanasi.',
    culturalSignificance: 'This image defines the classical paradigm of Buddhist art. Its serene, inward-looking expression and diaphanous robes became the definitive model for Buddha images throughout Asia.',
    materialsTechnique: 'Carved from Chunar sandstone. The figure exhibits the "wet drapery" technique typical of the Sarnath school of Gupta sculpture.',
    collectionName: 'Sarnath Museum, Archaeological Survey of India',
    image: '/assets/images/04-sarnath-buddha.jpg',
    imageSource: 'Wikimedia Commons (archival photograph, Catalogue of the Museum of Archaeology at Sarnath, 1914)',
    license: 'Public Domain (CC-PD)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Buddha_preaching_his_First_Sermon_(Sarnath).jpg'
  },
  {
    id: 'nataraja',
    title: 'Shiva as Lord of Dance (Nataraja)',
    eraLabel: 'Late 11th c. CE',
    period: 'Chola Dynasty',
    category: 'Sculpture / Bronze',
    description: 'Shiva performing the cosmic dance of destruction and creation (ananda tandava), encircled by a ring of flames, cast by the lost-wax process.',
    historicalContext: 'Produced during the Chola dynasty in South India, a period renowned for its exceptional bronze metallurgy and temple architecture.',
    culturalSignificance: 'A masterpiece of Hindu iconography. It visually encapsulates the Hindu concepts of cyclical time, cosmic creation, destruction, and liberation.',
    materialsTechnique: 'Solid bronze cast using the lost-wax process. The intricate details of the prabhamandala (aureole of fire) and the flying locks of hair demonstrate supreme metallurgical skill.',
    collectionName: 'The Metropolitan Museum of Art, New York, USA',
    image: '/assets/images/05-nataraja.jpg',
    imageSource: 'The Metropolitan Museum of Art — Open Access (images.metmuseum.org)',
    license: 'CC0 1.0 (Met Open Access programme)',
    sourceUrl: 'https://www.metmuseum.org/art/collection/search/39328'
  },
  {
    id: 'mughal-miniature',
    title: 'Jahangir Preferring a Sufi Shaikh to Kings',
    eraLabel: 'c. 1615–1618',
    period: 'Mughal Empire',
    category: 'Painting / Miniature',
    description: 'A documented Mughal court miniature in which Emperor Jahangir, seated on an hourglass throne, presents a book to a Sufi Shaikh.',
    historicalContext: 'Painted by the master artist Bichitr for Emperor Jahangir. The hourglass throne symbolizes the emperor\'s awareness of mortality.',
    culturalSignificance: 'A profound statement of Mughal imperial ideology, showing the emperor favoring spiritual authority (the Sufi Shaikh) over temporal power (represented by the Ottoman Sultan and King James I of England).',
    materialsTechnique: 'Opaque watercolor, gold, and ink on paper. Exhibits exquisite detail, vibrant pigments, and European influences (such as the cherubs).',
    collectionName: 'Freer Gallery of Art, National Museum of Asian Art, Smithsonian Institution, Washington, DC',
    image: '/assets/images/06-mughal-miniature.jpg',
    imageSource: 'Wikimedia Commons (image credit: Smithsonian Freer Gallery press image)',
    license: 'Public Domain (CC-PD)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bichitr_-_Jahangir_preferring_a_sufi_sheikh_to_kings.jpg'
  },
  {
    id: 'rajput-bani-thani',
    title: 'Radha (Bani Thani)',
    eraLabel: 'c. 1750',
    period: 'Rajput Painting',
    category: 'Painting / Miniature',
    description: 'The iconic Kishangarh portrait of Bani Thani — the poet-singer Vishnupriya idealised as Radha, with elongated lotus eyes and arched brows.',
    historicalContext: 'Painted by Nihal Chand at the Kishangarh court under the patronage of Raja Savant Singh, who was deeply devoted to Krishna.',
    culturalSignificance: 'Often called the "Mona Lisa of India," it represents the pinnacle of the Kishangarh school of Rajput painting, setting a unique, highly stylized standard for beauty.',
    materialsTechnique: 'Opaque watercolor and gold on paper. Characterized by extreme stylization: exaggeratedly arched eyebrows, lotus-petal eyes, and a sharp, pointed chin.',
    collectionName: 'National Museum, New Delhi, India',
    image: '/assets/images/07-rajput-bani-thani.jpg',
    imageSource: 'Wikimedia Commons (photograph of National Museum, New Delhi exhibit)',
    license: 'Public Domain (CC-PD)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:4_Radha_(Bani_Thani),_Kishangarh,_ca._1750,_National_Museum_New_Delhi.jpg'
  },
  {
    id: 'ravi-varma',
    title: 'Shakuntala Lost in Thoughts',
    eraLabel: '1901',
    period: 'Modern Indian Art',
    category: 'Painting / Oil',
    description: 'Ravi Varma\'s romantic treatment of Shakuntala from Kalidasa\'s classic drama — the heroine lost in thought, awaiting the return of her beloved Dushyanta.',
    historicalContext: 'Painted at the turn of the 20th century, a time when Ravi Varma was establishing a new visual vocabulary for Indian mythology using European academic techniques.',
    culturalSignificance: 'Raja Ravi Varma revolutionized Indian art by bringing pan-Indian mythological themes to the masses through oleograph prints, deeply influencing modern Indian visual culture and cinema.',
    materialsTechnique: 'Oil on canvas. Employs European academic realism, dramatic lighting (chiaroscuro), and perspective, adapted to Indian subjects.',
    collectionName: 'Sree Chitra Art Gallery, Thiruvananthapuram, Kerala, India',
    image: '/assets/images/08-ravi-varma-shakuntala.jpg',
    imageSource: 'Wikimedia Commons (image credited via Google Arts & Culture scanning project)',
    license: 'Public Domain (CC-PD)',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Raja_Ravi_Varma,_Shakuntala_lost_in_thoughts_(1901).jpg'
  },
  {
    id: 'bharat-mata',
    title: 'Bharat Mata',
    eraLabel: '1905',
    period: 'Bengal School',
    category: 'Painting / Watercolour',
    description: 'The famous image of Mother India as a four-armed goddess in an ochre sari, painted by Abanindranath Tagore in response to the Partition of Bengal.',
    historicalContext: 'Created during the Swadeshi movement against the 1905 partition of Bengal. It was a conscious rejection of Western academic art in favor of pan-Asian aesthetics.',
    culturalSignificance: 'The first visual representation of India as a mother goddess. It became an immensely powerful icon for the Indian independence movement.',
    materialsTechnique: 'Watercolor on paper using the Japanese wash technique. The ethereal, hazy quality was intended to evoke spiritual depth rather than material reality.',
    collectionName: 'Victoria Memorial Hall, Kolkata, West Bengal, India',
    image: '/assets/images/09-bharat-mata.jpg',
    imageSource: 'Wikimedia Commons (scan of the painting)',
    license: 'Public Domain (CC-PD) — artist died 1951',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bharat_Mata_by_Abanindranath_Tagore.jpg'
  },
  {
    id: 'three-girls',
    title: 'Three Girls',
    eraLabel: '1935',
    period: 'Modern Indian Art',
    category: 'Painting / Oil',
    description: 'Three young Indian women seated together in quiet introspection, painted in Amrita Sher-Gil\'s flattened, colour-rich style.',
    historicalContext: 'Painted shortly after Sher-Gil returned to India from Paris. It marks her deliberate shift towards capturing the melancholy and reality of Indian village life.',
    culturalSignificance: 'Sher-Gil is a pioneer of modern Indian art. This painting represents a synthesis of Western post-impressionism with the vibrant color palette and themes of Indian classical art.',
    materialsTechnique: 'Oil on canvas. Characterized by a rich, earthy color palette, bold brushstrokes, and a rejection of naturalistic modeling in favor of flat areas of color.',
    collectionName: 'National Gallery of Modern Art, New Delhi, India',
    image: '/assets/images/10-three-girls.jpg',
    imageSource: 'Wikimedia Commons (image credited via Google Arts & Culture / NGMA)',
    license: 'Public Domain (CC-PD) — artist died 1941',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Amrita_Sher-Gil_Group_of_Three_Girls.jpg'
  }
];
